// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package most

var TableNames = struct {
	Customers      string
	CustomersRoles string
	Roles          string
}{
	Customers:      "customers",
	CustomersRoles: "customers_roles",
	Roles:          "roles",
}
