// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package most

var TableNames = struct {
	Orders     string
	Roles      string
	Users      string
	UsersRoles string
}{
	Orders:     "orders",
	Roles:      "roles",
	Users:      "users",
	UsersRoles: "users_roles",
}
