SELECT get_current_ts_config ();
SHOW default_text_search_config;

SELECT to_tsvector('english', 'a fat  cat sat on a mat - it ate age a fat fff fff fff fff fff fff fff fff fff fff fff fff fff fff fff rats');
SELECT to_tsquery('english', 'The & Fat & Rats');
SELECT to_tsvector('english', u.login || u.description) FROM users u;
SELECT to_tsvector('russian', u.login || u.description) FROM users u;
SELECT to_tsvector('english', u.description) AS en, to_tsvector(u.description) AS ru FROM users u;

SELECT u.login || u.description AS doument FROM users u;

SELECT 'a fat cat sat on a mat and ate a fat rat'::tsvector @@ 'cat & rat'::tsquery;
SELECT 'fat & cow'::tsquery @@ 'a fat cat sat on a mat and ate a fat rat'::tsvector;

SELECT to_tsvector('a fat cat sat on a mat and ate a fat rat') @@ to_tsquery('cats & rats');
SELECT to_tsquery('cats & rats');

-- начало

CREATE TABLE public.web (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL,
	description text NULL,
	price numeric NOT NULL DEFAULT 0,
	CONSTRAINT web_pk PRIMARY KEY (id)
);

-- простой вариант (динамический - на лету)

-- COALESCE для обработки полей со значением NULL и включением в результаты поиска (иначе если одно поле будет null, то все остальные поля будут проигнорированы) 

CREATE INDEX web_description_idx ON web USING GIN (to_tsvector('russian', title || ' ' || description));

SELECT
	id,
	title,
	description
FROM
	web
WHERE
	to_tsvector('russian', COALESCE(title , '') || ' ' || COALESCE(description, '')) @@ to_tsquery('огурец');

-- 'russian' указывать обязательно чтобы при поиске использовался индекс

-- сложный вариант но лучше с отдельной колонкой (с подготовкой данных для поиска)

-- поля без веса
ALTER TABLE web 
	ADD COLUMN textsearch tsvector
		GENERATED ALWAYS AS (to_tsvector('russian', COALESCE(title , '') || ' ' || COALESCE(description , ''))) STORED;

CREATE INDEX web_textsearch_idx ON web USING GIN (textsearch);

-- поля с весом
ALTER TABLE web 
	ADD COLUMN textsearchweight tsvector
		GENERATED ALWAYS AS (
		setweight(to_tsvector('russian', COALESCE(title , '')), 'A') ||
		setweight(to_tsvector('russian', COALESCE(description , '')), 'B')
		) STORED;

CREATE INDEX web_textsearchweight_idx ON web USING GIN (textsearchweight);	

--

SELECT
	id,
	title,
	description
FROM
	web
WHERE
	textsearchweight @@ to_tsquery('помидор:AB | ог:*BA');

SELECT
	id,
	title,
	ts_rank_cd(textsearchweight, to_tsquery('корабль'), 2 | 8) AS RANK
FROM
	web
WHERE
	to_tsquery('корабль') @@ textsearchweight
ORDER BY
	RANK DESC
;






