INSERT INTO films
(title, description, category_id, release_year, price)
SELECT title, description, category_id, release_year, price
FROM films WHERE id IN (349, 696);

INSERT INTO documents 
	(title, description, category_id, release_year, price, created_at, updated_at, deleted_at, is_flag, "data")
SELECT title, description, category_id, release_year, price, created_at, updated_at, deleted_at, is_flag, "data" FROM documents_old;

INSERT INTO documents  
	(title, description, category_id, release_year, price, created_at, updated_at, deleted_at)
SELECT title, description, category_id, release_year, price, created_at, updated_at, deleted_at FROM documents1 ORDER BY updated_at DESC LIMIT 10000000;

SELECT count(*) FROM documents;
SELECT count(*) FROM documents1;

UPDATE documents SET created_at = now() - INTERVAL '3 MONTH', updated_at = now() - INTERVAL '2 MONTH' WHERE id < 1001;
UPDATE documents SET created_at = now() - INTERVAL '5 MONTH', updated_at = now() - INTERVAL '4 MONTH' WHERE id > 1000;

SELECT start_at, to_timestamp(extract(epoch from start_at::timestamptz)) FROM manticore_breaker;

DELETE FROM documents WHERE id > 4000000;

UPDATE documents SET id = id - 1;
UPDATE documents SET updated_at = now(), deleted_at = NULL WHERE id > 4;
UPDATE documents SET DATA = '{"id":12, "name":"funtik", "price":34.67}';
UPDATE documents SET is_flag = true;


SELECT * FROM documents1 ORDER BY updated_at DESC LIMIT 10;


CREATE TABLE public.documents (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	title text NOT NULL,
	description text NOT NULL,
	category_id int8 NOT NULL DEFAULT 3,
	release_year int4 NOT NULL DEFAULT 2005,
	price numeric(10, 2) NOT NULL DEFAULT 2.76,
	created_at timestamp NOT NULL DEFAULT now(),
	updated_at timestamp NOT NULL DEFAULT now(),
	deleted_at timestamp NULL,
	is_flag bool NOT NULL DEFAULT false,
	"data" jsonb NULL,
	CONSTRAINT documents_pk_1 PRIMARY KEY (id)
);
CREATE INDEX documents_deleted_at_idx1 ON public.documents USING btree (deleted_at);
CREATE INDEX documents_updated_at_idx2 ON public.documents USING btree (updated_at);
