CREATE TABLE IF NOT EXISTS `retro_bonus_details` (
    id bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'ИД',
    ekk                         BIGINT,
    branch_ekk                  BIGINT,
    complex_sbu                 TEXT,
    bonus_program_code          TEXT,
    bonus_program_name          TEXT,
    bonus_program_guid          UUID,
    payout_frequency            TEXT,
    sales_region_guid           UUID,
    sales_region_name           TEXT,
    additional_condition        BOOLEAN NOT NULL DEFAULT FALSE,
    nomenclature_condition      TEXT,
    conditional_plan            numeric(10,2),
    measure_unit_id             TEXT,
    currency_id                 TEXT,
    plan_for_amount             BOOLEAN NOT NULL DEFAULT FALSE,
    is_cumulative_total         BOOLEAN NOT NULL DEFAULT FALSE,
    conditional_fact            numeric(10,2),
    condition_is_met            BOOLEAN NOT NULL DEFAULT FALSE,
    additional_conditional_fact DOUBLE PRECISION,
    additional_condition_is_met BOOLEAN NOT NULL DEFAULT FALSE,
    complex_retro_bonus         BOOLEAN NOT NULL DEFAULT FALSE,
    agreement_guid              UUID,
    date_begin                  TIMESTAMP,
    date_end                    TIMESTAMP,
    date_formation_begin        TIMESTAMP,
    date_formation_end          TIMESTAMP,
    calculation_date            TIMESTAMP,
    PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci COMMENT='retro_bonus_details';
