CREATE TABLE public.users
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    login       text      NOT NULL,
    description text NULL,
    price       numeric   NOT NULL DEFAULT 0,
    summa_one   float4    NOT NULL DEFAULT 0,
    summa_two   float8    NOT NULL DEFAULT 0,
    cnt         int4      NOT NULL DEFAULT 0,
    cnt2        int2      NOT NULL DEFAULT 0,
    cnt4        int4      NOT NULL DEFAULT 0,
    cnt8        int8      NOT NULL DEFAULT 0,
    sharding_id uuid      NULL,
    is_online   bool      NOT NULL DEFAULT false,
    metrika     jsonb NULL,
    duration    int8      NOT NULL DEFAULT 0,
    "data"      bytea NULL,
    alias       _text     NULL,
    created_at  timestamp NOT NULL DEFAULT now(),
    updated_at  timestamp NOT NULL DEFAULT now(),
    deleted_at  timestamp NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE public.roles
(
    id          int8 GENERATED BY DEFAULT AS IDENTITY,
    code        text      NOT NULL,
    description text      NOT NULL,
    CONSTRAINT roles_pk PRIMARY KEY (id)
);

CREATE TABLE public.users_roles
(
    user_id int8 NOT NULL,
    role_id int8 NOT NULL,
    CONSTRAINT users_roles_pk PRIMARY KEY (user_id, role_id)
);
ALTER TABLE public.users_roles
    ADD CONSTRAINT users_roles_fk FOREIGN KEY (user_id) REFERENCES users (id) ON
        UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE public.users_roles
    ADD CONSTRAINT users_roles_fk_1 FOREIGN KEY (role_id) REFERENCES roles (id) ON
        UPDATE CASCADE ON DELETE CASCADE;

CREATE TABLE public.orders
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY,
    user_id    int8 NULL,
    "number"   int4      NOT NULL DEFAULT 0,
    status     text      NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    updated_at TIMESTAMP NOT NULL DEFAULT now(),
    deleted_at TIMESTAMP NULL,
    CONSTRAINT orders_pk PRIMARY KEY (id)
);
ALTER TABLE public.orders
    ADD CONSTRAINT orders_fk FOREIGN KEY (user_id) REFERENCES users (id) ON
        UPDATE CASCADE ON DELETE RESTRICT;

INSERT INTO public.users
(login, price, summa_one, summa_two, cnt2, cnt4, cnt8, is_online)
VALUES ('testLogin', 0, 0, 0, 0, 0, 0, false);
INSERT INTO public.users
(login, price, summa_one, summa_two, cnt2, cnt4, cnt8, is_online)
VALUES ('gpscdIEk', 0, 0, 0, 0, 0, 0, false);
INSERT INTO public.users
(login, price, summa_one, summa_two, cnt2, cnt4, cnt8, is_online)
VALUES ('v3iwypkK', 0, 0, 0, 0, 0, 0, false);


CREATE TABLE public.trees (
	id serial NOT NULL,
	parent_id int4 NOT NULL DEFAULT 0,
	keyl int4 NOT NULL DEFAULT 1,
	keyr int4 NOT NULL DEFAULT 2,
	"level" int4 NOT NULL DEFAULT 1,
	"tree" int4 NOT NULL DEFAULT 1,
	"name" TEXT NOT NULL,
	CONSTRAINT trees_pk PRIMARY KEY (id)
);

CREATE TABLE public.tree (
	id serial NOT NULL,
	parent_id int4 NOT NULL DEFAULT 0,
	keyl int4 NOT NULL DEFAULT 1,
	keyr int4 NOT NULL DEFAULT 2,
	"level" int4 NOT NULL DEFAULT 1,
	"name" TEXT NOT NULL,
	CONSTRAINT tree_pk PRIMARY KEY (id)
);

