// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package tp

var TableNames = struct {
	Minio      string
	Orders     string
	Roles      string
	Users      string
	UsersRoles string
}{
	Minio:      "minio",
	Orders:     "orders",
	Roles:      "roles",
	Users:      "users",
	UsersRoles: "users_roles",
}
